create table if not exists public.telegram_webhook_idempotency (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists telegram_webhook_idempotency_expires_at_idx
  on public.telegram_webhook_idempotency (expires_at);

alter table public.telegram_webhook_idempotency enable row level security;

create or replace function public.claim_telegram_webhook_idempotency(
  p_idempotency_key text,
  p_event_type text,
  p_payload jsonb default '{}'::jsonb,
  p_ttl interval default interval '24 hours'
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed boolean;
begin
  delete from public.telegram_webhook_idempotency
  where expires_at < now();

  insert into public.telegram_webhook_idempotency (
    idempotency_key,
    event_type,
    payload,
    expires_at
  )
  values (
    p_idempotency_key,
    p_event_type,
    coalesce(p_payload, '{}'::jsonb),
    now() + p_ttl
  )
  on conflict (idempotency_key) do update
    set event_type = excluded.event_type,
        payload = excluded.payload,
        expires_at = excluded.expires_at
    where public.telegram_webhook_idempotency.expires_at < now()
  returning true into claimed;

  return coalesce(claimed, false);
end;
$$;
