create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  recorded_at timestamptz not null default now(),
  usage_date text not null,
  provider text not null check (provider in ('gemini', 'claude')),
  model text not null,
  source text not null check (source in ('chart', 'betting', 'lottery', 'test')),
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  estimated_cost_usd numeric(12,6) not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists ai_usage_usage_date_idx on public.ai_usage (usage_date desc);
create index if not exists ai_usage_recorded_at_idx on public.ai_usage (recorded_at desc);
create index if not exists ai_usage_provider_idx on public.ai_usage (provider);
create index if not exists ai_usage_source_idx on public.ai_usage (source);

alter table public.ai_usage enable row level security;

grant select, insert on public.ai_usage to service_role;
grant usage, select on sequence public.ai_usage_id_seq to service_role;
