create table if not exists public.betting_analysis_snapshots (
  id bigint generated by default as identity primary key,
  game_id text not null unique,
  date text not null,
  home text not null,
  away text not null,
  kickoff_unix bigint not null,
  odds jsonb not null,
  correct_score jsonb,
  analysis jsonb not null,
  verified_confirmed boolean,
  verified_confidence integer,
  verified_comment text,
  revised_after_reject boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists betting_analysis_snapshots_date_idx on public.betting_analysis_snapshots (date);
create index if not exists betting_analysis_snapshots_kickoff_unix_idx on public.betting_analysis_snapshots (kickoff_unix);

alter table public.betting_analysis_snapshots enable row level security;
