create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  "timestamp" timestamptz not null default now(),
  level text not null check (level in ('debug', 'info', 'warn', 'error')),
  message text not null,
  context jsonb not null default '{}'::jsonb,
  source text not null
);

create index if not exists logs_timestamp_idx on public.logs ("timestamp" desc);
create index if not exists logs_level_idx on public.logs (level);
create index if not exists logs_source_idx on public.logs (source);

alter table public.logs enable row level security;
